-- Libera a criação de usuários locais sem o prefixo C##
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

-- 1. Cria o usuário HR
CREATE USER HR 
IDENTIFIED BY hr
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE TEMP
QUOTA unlimited on users
QUOTA 0 on system;

-- 2. Concede permissões de acesso
GRANT CONNECT, RESOURCE TO HR;

-- 3. Concede privilégios de criação de objetos
GRANT CREATE SESSION, CREATE VIEW, CREATE TABLE, ALTER SESSION, CREATE SEQUENCE, CREATE PROCEDURE, CREATE TRIGGER TO HR;
GRANT CREATE SYNONYM, CREATE DATABASE LINK, UNLIMITED TABLESPACE TO HR;